pairing = [["CS", "S", 0],
["FB", "F", 0],
["VK", "V", 0],
["HO", "F", 0],
["SO", "K", 0],
["FK", "B", 0],
["VS", "C", 0],
["PS", "H", 0],
["HH", "P", 0],
["KH", "V", 0],
["PV", "V", 0],
["CB", "N", 0],
["BB", "N", 0],
["HB", "B", 0],
["HV", "O", 0],
["NC", "H", 0],
["NF", "B", 0],
["HP", "B", 0],
["HK", "S", 0],
["SF", "O", 0],
["ON", "K", 0],
["VN", "V", 0],
["SB", "H", 0],
["SK", "H", 0],
["VH", "N", 0],
["KN", "C", 0],
["CC", "N", 0],
["BF", "H", 0],
["SN", "N", 0],
["KP", "B", 0],
["FO", "N", 0],
["KO", "V", 0],
["BP", "O", 0],
["OK", "F", 0],
["HC", "B", 0],
["NH", "O", 0],
["SP", "O", 0],
["OO", "S", 0],
["VC", "O", 0],
["PC", "F", 0],
["VB", "O", 0],
["FF", "S", 0],
["BS", "F", 0],
["KS", "F", 0],
["OV", "P", 0],
["NB", "O", 0],
["CF", "F", 0],
["SS", "V", 0],
["KV", "K", 0],
["FP", "F", 0],
["KC", "C", 0],
["PF", "C", 0],
["OS", "C", 0],
["PN", "B", 0],
["OP", "C", 0],
["FN", "F", 0],
["OF", "C", 0],
["NP", "C", 0],
["CK", "N", 0],
["BN", "K", 0],
["BO", "K", 0],
["OH", "S", 0],
["BH", "O", 0],
["SH", "N", 0],
["CH", "K", 0],
["PO", "V", 0],
["CN", "N", 0],
["BV", "F", 0],
["FV", "B", 0],
["VP", "V", 0],
["FS", "O", 0],
["NV", "P", 0],
["PH", "C", 0],
["HN", "P", 0],
["VV", "C", 0],
["NK", "K", 0],
["CO", "N", 0],
["NS", "P", 0],
["VO", "P", 0],
["CP", "V", 0],
["OC", "S", 0],
["PK", "V", 0],
["NN", "F", 0],
["SC", "P", 0],
["BK", "F", 0],
["BC", "P", 0],
["FH", "B", 0],
["OB", "O", 0],
["FC", "N", 0],
["PB", "N", 0],
["VF", "N", 0],
["PP", "S", 0],
["HS", "O", 0],
["HF", "N", 0],
["KK", "C", 0],
["KB", "N", 0],
["SV", "N", 0],
["KF", "K", 0],
["CV", "N", 0],
["NO", "P", 0]]

occurance = [["B", 0], ["C", 0], ["F", 0], ["H", 0], ["K", 0], ["N", 0],
             ["O", 0], ["P", 0], ["S", 0], ["V", 0]]

starter = [
    "C", "N", "B", "P", "H", "F", "B", "O", "P", "C", "S", "P", "K", "O", "F",
    "N", "H", "V", "K", "V"
]

chemistry = [["CS", "S", 0],
["FB", "F", 0],
["VK", "V", 0],
["HO", "F", 0],
["SO", "K", 0],
["FK", "B", 0],
["VS", "C", 0],
["PS", "H", 0],
["HH", "P", 0],
["KH", "V", 0],
["PV", "V", 0],
["CB", "N", 0],
["BB", "N", 0],
["HB", "B", 0],
["HV", "O", 0],
["NC", "H", 0],
["NF", "B", 0],
["HP", "B", 0],
["HK", "S", 0],
["SF", "O", 0],
["ON", "K", 0],
["VN", "V", 0],
["SB", "H", 0],
["SK", "H", 0],
["VH", "N", 0],
["KN", "C", 0],
["CC", "N", 0],
["BF", "H", 0],
["SN", "N", 0],
["KP", "B", 0],
["FO", "N", 0],
["KO", "V", 0],
["BP", "O", 0],
["OK", "F", 0],
["HC", "B", 0],
["NH", "O", 0],
["SP", "O", 0],
["OO", "S", 0],
["VC", "O", 0],
["PC", "F", 0],
["VB", "O", 0],
["FF", "S", 0],
["BS", "F", 0],
["KS", "F", 0],
["OV", "P", 0],
["NB", "O", 0],
["CF", "F", 0],
["SS", "V", 0],
["KV", "K", 0],
["FP", "F", 0],
["KC", "C", 0],
["PF", "C", 0],
["OS", "C", 0],
["PN", "B", 0],
["OP", "C", 0],
["FN", "F", 0],
["OF", "C", 0],
["NP", "C", 0],
["CK", "N", 0],
["BN", "K", 0],
["BO", "K", 0],
["OH", "S", 0],
["BH", "O", 0],
["SH", "N", 0],
["CH", "K", 0],
["PO", "V", 0],
["CN", "N", 0],
["BV", "F", 0],
["FV", "B", 0],
["VP", "V", 0],
["FS", "O", 0],
["NV", "P", 0],
["PH", "C", 0],
["HN", "P", 0],
["VV", "C", 0],
["NK", "K", 0],
["CO", "N", 0],
["NS", "P", 0],
["VO", "P", 0],
["CP", "V", 0],
["OC", "S", 0],
["PK", "V", 0],
["NN", "F", 0],
["SC", "P", 0],
["BK", "F", 0],
["BC", "P", 0],
["FH", "B", 0],
["OB", "O", 0],
["FC", "N", 0],
["PB", "N", 0],
["VF", "N", 0],
["PP", "S", 0],
["HS", "O", 0],
["HF", "N", 0],
["KK", "C", 0],
["KB", "N", 0],
["SV", "N", 0],
["KF", "K", 0],
["CV", "N", 0],
["NO", "P", 0]]

temp = ""
for x in range(len(starter)-1):
  temp = starter[x]+starter[x+1]
  for y in range(len(pairing)):
    if temp in pairing[y]:
      pairing[y][2] += 1
      
for x in range(len(starter)):
  for y in range(len(occurance)):
    if occurance[y][0] == starter[x]:
      occurance[y][1] += 1

for x in range(40):
  for v in range(len(pairing)):
    if pairing[v][2] !=0:
      for j in range(len(occurance)):
        if pairing[v][1] == occurance[j][0]:
          occurance[j][1] += pairing[v][2]
      temp1 = pairing[v][0][0] + pairing[v][1]
      temp2 = pairing[v][1] + pairing[v][0][1]
      print(temp1 + temp2)
      for i in range(len(chemistry)):
        if temp1 in chemistry[i] or temp2 in chemistry[i]:
          chemistry[i][2] += pairing[v][2]
        # else:
        #   print("ERROR")
  pairing.clear()
  pairing =chemistry.copy()
  chemistry = [["CS", "S", 0],
["FB", "F", 0],
["VK", "V", 0],
["HO", "F", 0],
["SO", "K", 0],
["FK", "B", 0],
["VS", "C", 0],
["PS", "H", 0],
["HH", "P", 0],
["KH", "V", 0],
["PV", "V", 0],
["CB", "N", 0],
["BB", "N", 0],
["HB", "B", 0],
["HV", "O", 0],
["NC", "H", 0],
["NF", "B", 0],
["HP", "B", 0],
["HK", "S", 0],
["SF", "O", 0],
["ON", "K", 0],
["VN", "V", 0],
["SB", "H", 0],
["SK", "H", 0],
["VH", "N", 0],
["KN", "C", 0],
["CC", "N", 0],
["BF", "H", 0],
["SN", "N", 0],
["KP", "B", 0],
["FO", "N", 0],
["KO", "V", 0],
["BP", "O", 0],
["OK", "F", 0],
["HC", "B", 0],
["NH", "O", 0],
["SP", "O", 0],
["OO", "S", 0],
["VC", "O", 0],
["PC", "F", 0],
["VB", "O", 0],
["FF", "S", 0],
["BS", "F", 0],
["KS", "F", 0],
["OV", "P", 0],
["NB", "O", 0],
["CF", "F", 0],
["SS", "V", 0],
["KV", "K", 0],
["FP", "F", 0],
["KC", "C", 0],
["PF", "C", 0],
["OS", "C", 0],
["PN", "B", 0],
["OP", "C", 0],
["FN", "F", 0],
["OF", "C", 0],
["NP", "C", 0],
["CK", "N", 0],
["BN", "K", 0],
["BO", "K", 0],
["OH", "S", 0],
["BH", "O", 0],
["SH", "N", 0],
["CH", "K", 0],
["PO", "V", 0],
["CN", "N", 0],
["BV", "F", 0],
["FV", "B", 0],
["VP", "V", 0],
["FS", "O", 0],
["NV", "P", 0],
["PH", "C", 0],
["HN", "P", 0],
["VV", "C", 0],
["NK", "K", 0],
["CO", "N", 0],
["NS", "P", 0],
["VO", "P", 0],
["CP", "V", 0],
["OC", "S", 0],
["PK", "V", 0],
["NN", "F", 0],
["SC", "P", 0],
["BK", "F", 0],
["BC", "P", 0],
["FH", "B", 0],
["OB", "O", 0],
["FC", "N", 0],
["PB", "N", 0],
["VF", "N", 0],
["PP", "S", 0],
["HS", "O", 0],
["HF", "N", 0],
["KK", "C", 0],
["KB", "N", 0],
["SV", "N", 0],
["KF", "K", 0],
["CV", "N", 0],
["NO", "P", 0]]

totals = []
for u in range(len(occurance)):
  totals.append(occurance[u][1])

print(totals)
totals.sort()
print(totals)
print(totals[len(totals)-1]-totals[0])

      
