outputs = [["bgefdac","bdace","ad","agcd"],
["aefdc","fbde","abdefc","dcgae"],
["bfg","bf","bf","bdgeca"],
["bdacfge","cd","cade","dcae"],
["cad","dc","dc","bedacfg"],
["dae","fadgbc","ecgd","aedcgf"],
["aefcbd","bgaf","afgb","dgb"],
["adceg","edbcagf","edf","fe"],
["dbc","dabge","abdgce","cegb"],
["cgfae","cb","gcdebaf","efgca"],
["cgdfe","afc","acf","af"],
["fdaegbc","gfbc","bdc","cb"],
["bdfgac","fcabedg","agd","dfbgcea"],
["bcag","dfeba","agbc","cbag"],
["bcgef","efgabc","dc","degfcb"],
["cefdabg","bacef","fcd","fegd"],
["eg","eg","bgadfce","baegc"],
["daegbf","ebfad","ceafb","bgde"],
["cg","gafdbce","cbdgf","gfdab"],
["cgdf","df","agbde","edgcbf"],
["gfeca","aecgfd","eagcf","fadcbeg"],
["gfeb","fe","badge","adfeb"],
["fa","edbcgf","dcgfe","adecb"],
["abcgd","dcabg","dgbafc","eg"],
["dbgec","adgbcf","dcefg","fc"],
["gdfb","fdbcaeg","gdfb","bf"],
["gfaebdc","acde","caed","dbafge"],
["bfdcaeg","eg","ega","ge"],
["ged","gbadfec","cdeafgb","acbfged"],
["egdcbf","dac","bcgfde","cbgedfa"],
["becf","dagef","befc","dbfae"],
["da","fdcab","cda","dac"],
["bae","ebdfc","ebgcad","bdefcga"],
["bdeaf","gebfadc","faecgb","dabfe"],
["badfe","egbf","efgb","gfecbda"],
["fbdgca","dgf","dfg","gfadecb"],
["edfacb","gecbf","dcg","dcbafe"],
["ebfg","cebdaf","cabegfd","gfecd"],
["gaceb","edfabg","cdfbag","cfbeg"],
["abcdgfe","gcba","fdabe","gb"],
["adefc","df","efcda","aecgbfd"],
["gae","cdbga","gea","eg"],
["fcgb","efgcdb","bcdeg","gb"],
["aed","dea","gface","agebdc"],
["gab","ebcgfd","fgdeabc","ab"],
["afgdc","gfbe","efa","bdegca"],
["dgf","df","afcd","dfg"],
["fg","efcg","fag","dafeg"],
["dbgfac","dbgce","ceagfdb","ba"],
["ebcgfda","db","ecdabf","daebgc"],
["cedgf","edbacgf","fbag","gdbea"],
["cdgbfe","gcbd","cb","cfb"],
["gcdfbea","gecb","febcgd","gbce"],
["dbcf","afgcedb","edcfag","cfbd"],
["ce","cgfab","cgdfba","cbe"],
["gb","dgecfb","gaefcd","bcg"],
["cedabgf","de","de","ed"],
["ecga","ecga","gfe","debfacg"],
["dgea","egad","eg","aegd"],
["fdbecg","abcfg","gbcfa","ae"],
["ce","dgbaefc","bdcae","fgcdbae"],
["bf","cebdfag","ebdfca","fb"],
["eafg","eg","gdcbaf","cdabfg"],
["agbdefc","agde","ad","da"],
["fdbcaeg","bagc","bdegaf","cfdbg"],
["feg","fg","bgfcde","dfga"],
["eadfbg","edfc","ecdgb","fecd"],
["gbcaed","cbged","degfcba","dfb"],
["ga","abgefd","ga","geaf"],
["bdacg","gcd","acdf","dcfa"],
["fdcea","gd","degb","dag"],
["gd","ecgd","dfbea","cfedagb"],
["dagc","badfegc","dgac","gdb"],
["caf","dcfeba","debfca","ecgdfa"],
["cbgdae","cagd","ecagbdf","cgedafb"],
["agcef","bfagedc","gacfe","fd"],
["cbdf","fecdg","bgedfa","bcaefg"],
["afb","gfabcd","bgfca","ba"],
["dgefba","dfcga","aecbdf","ebgc"],
["edgacf","fdegc","cfged","egf"],
["bgafd","fabc","fcbgaed","edagbc"],
["dcgafeb","bcfdge","dcfeab","cge"],
["ae","gcfedba","ae","fae"],
["geab","aefdb","cdafb","eb"],
["gd","dgf","dfg","gd"],
["efabcd","edgcfb","dge","bgea"],
["fa","bgcdea","eaf","cfgade"],
["gdefb","gfcadbe","facdbg","aegcdbf"],
["fdcbg","bcgedaf","bcd","efbgc"],
["bg","bg","ecbfa","abcg"],
["defab","bdcgaf","dgbe","dbfgea"],
["gb","cbgf","fdcbea","abg"],
["baged","eadbf","bg","gfecda"],
["afbcegd","gebc","abe","abe"],
["cafbg","acbegfd","eg","cfabg"],
["bagfd","bagdf","cdbagfe","cfa"],
["cbe","bgcf","cgaeb","cegba"],
["efdab","eafbd","cafdbeg","fc"],
["baf","gcadbef","bfa","dbgfe"],
["agcdbf","bgdc","cdgb","bda"],
["dfbega","abgd","dfecbag","gfdeb"],
["eacfdb","acbef","cfa","bdcf"],
["cagefb","fca","ac","fegbdc"],
["gaebcd","gde","bcde","bcde"],
["bcdge","cfbaegd","ebadg","feba"],
["de","dbe","feabdgc","gdae"],
["fecga","adg","gcdebfa","cefgadb"],
["ga","ag","gace","agdbcf"],
["ca","fbdegc","dcaf","gcfab"],
["bce","gdec","cdge","bagdc"],
["cdg","gbafd","gc","cabdegf"],
["cgbd","edgfa","cbdg","afged"],
["egfdac","acfdeg","dgecfba","fcdab"],
["ba","fadce","gadecbf","ba"],
["ge","befgdca","fcebd","cfgeb"],
["fba","caefbd","fb","gfcab"],
["gebac","ef","agebdfc","edaf"],
["efda","cagefb","defa","aec"],
["dg","cagdb","gdabfc","dag"],
["bf","aecbg","gbfa","dgaceb"],
["edc","gdbe","bcdae","fbagdec"],
["bfedgc","gcdbaf","bd","agdb"],
["fbecga","dfegbca","fd","bfgaed"],
["dbcefag","afe","bcega","eaf"],
["dcbagef","afecdbg","ebcdafg","gb"],
["ad","agdb","dcfebg","gadbfc"],
["gbd","fgbdc","dfgabce","gadfc"],
["fcgdaeb","fdebcga","abfecg","fgceba"],
["afgebd","gfa","bedagf","gfdc"],
["dc","cd","aecbfd","dfaebcg"],
["ca","debfa","cfedab","baedc"],
["bed","bde","bd","ecadg"],
["dabfgc","fbegd","fe","edcbfa"],
["bd","bd","cbaefdg","fegab"],
["fbeda","aecbfd","gbfcd","fbadeg"],
["gbefca","ecfagb","fagb","cegdb"],
["age","gea","egfc","ega"],
["dgcbf","gafebcd","cdf","bfdaceg"],
["bga","ga","gab","bcfdgae"],
["dbacgf","dceg","gdfecab","gd"],
["da","adb","egbafdc","adb"],
["cfe","fgebac","gedcafb","cf"],
["gcf","abcfdg","fg","cbfad"],
["dc","dc","acgfb","cd"],
["dbfcage","ebdaf","bca","bdeac"],
["efa","fcbgae","dfeg","bgacfd"],
["cbg","agdb","aefcbd","agceb"],
["ce","ecd","egfadc","gdeca"],
["ba","dfab","ab","ecbdgf"],
["dca","acd","afcgebd","efacg"],
["abcdf","gbef","ceb","ceb"],
["ecabgf","ba","dcaegb","cfebag"],
["aeb","bea","ebgc","be"],
["efabgcd","bdgfc","debcgaf","ebcfgda"],
["dbeag","afbc","abfc","ca"],
["fcaed","cgbfea","dfbg","bagefc"],
["fecadg","cbgd","dfceag","fcgead"],
["afgdb","gecfadb","cbegaf","cb"],
["fad","gafce","badec","afdegcb"],
["bce","gdecfb","ceda","ec"],
["cdfa","fdac","agfcebd","fcdgea"],
["cfdg","bfcea","aegdcb","gef"],
["edcfab","dfgcae","dfga","df"],
["gaeb","dcaeb","eabg","acfgebd"],
["dcbeafg","cfedabg","egdb","degb"],
["ad","bdae","bfeag","aedb"],
["fagdc","dfae","fagecb","dcgfb"],
["egdab","edgcfa","ad","bgcafed"],
["gafe","aebgd","ae","baegd"],
["edfca","fge","egf","agec"],
["gecafb","cfdgb","agf","gfa"],
["bfeac","ecdag","fbdc","fdcb"],
["abcfed","cfbga","fec","efc"],
["ebdgac","gacfe","efg","feg"],
["badce","efbd","deacb","daf"],
["gf","fga","defba","gf"],
["egbf","cbefdg","gcfeabd","bgfaecd"],
["bedgfc","fg","dfg","eadbfcg"],
["dgeacb","ebdcagf","ba","facb"],
["fcg","decgab","efdc","cf"],
["aegfcdb","adec","agedcf","ca"],
["edbcg","gadfec","bdacf","fde"],
["gfea","bag","fdgeab","ga"],
["dagecfb","bdfc","fcgeda","bceagfd"],
["cebgda","efcbg","edag","dgecb"],
["abcfdge","fbc","bc","efgcb"],
["defbg","dcefagb","af","aebdc"],
["gdf","cfadbg","acebfd","fcaegd"],
["bc","cfedg","edfabg","geabd"],
["befcda","fecgadb","cgebad","dfga"],
["fgace","cbefad","eafcg","ge"],
["ecb","fecd","cgaedb","ebdfa"],
["gafce","cfe","cdgabf","gacefd"],
["defgca","dgf","caefbdg","begfa"],
["gbfea","dbfgea","aebfgdc","dcgfba"],
["edgab","cg","ecg","gec"],
["gbced","bdacfge","fcgeab","fgbd"],
["bagde","bfg","egcfd","bf"],
["afegcd","facd","eagfbdc","fce"],
["beaf","egabdc","gbedcf","gbf"]]

while 17 == 16:
# #Used to edit the text file and create text file to make the bingo boards into an array
# with open('outputdigitdata.txt','r') as f:
#     contents = f.read()
#     #changedtxt = contents.replace(" ", ",")
#     #changetxt = changedtxt.replace(",", "+,+")
#     changedtxt = contents.replace("\n", "\"],\n[\"")
# with open('editedoutputdigitdata.txt', 'w') as g:
#   g.writelines(changedtxt)
    print("\" Hello World \"")


knowntotal = 0

for i in range(len(outputs)):
    for x in range(len(outputs[0])):
        if len(outputs[i][x]) == 2 or len(outputs[i][x]) == 3 or len(outputs[i][x]) == 4 or len(outputs[i][x]) == 7:
            print(len(outputs[i][x]), outputs[i][x])
            knowntotal +=1


print(knowntotal)
